### ISSUE TITLE
Unable to build production

### ISSUE THREAD

**Issue by syphernl** [CIMonitor/CIMonitor#161]
### What

The CI of this project is showing success, however when updating to this version I'm running into a few issues:

- First run of `make build-production` ends with: `Please run Mix again.` and doesn't seem to generate assets (like it used to)
- A second run of `make build-production` results in:
```
yarn install v1.22.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.91s.
yarn production
yarn run v1.22.0
$ NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
/srv/cimonitor/app/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/srv/cimonitor/app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/srv/cimonitor/app/back-end/domain/cimonitor/VersionChecker.js:2:16)
    at Module._compile (/srv/cimonitor/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/srv/cimonitor/app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/srv/cimonitor/app/webpack.mix.js:4:24)
    at Module._compile (/srv/cimonitor/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/srv/cimonitor/app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/srv/cimonitor/app/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (/srv/cimonitor/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/srv/cimonitor/app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/srv/cimonitor/app/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/srv/cimonitor/app/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /srv/cimonitor/app/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/srv/cimonitor/app/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/srv/cimonitor/app/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/srv/cimonitor/app/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /srv/cimonitor/app/node_modules/webpack-cli/bin/cli.js:49:8
error Command failed with exit code 1.
```
- If I manually execute `npm install semver --save` and run `make build-production` again the build goes further and eventually finishes with ` DONE  Compiled successfully in 18393ms`. 

- All is fine, until I try to start it:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/srv/cimonitor/app/back-end/server.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

- After a manual `npm install` Cypress is being installed and the application works fine. All runs above have been made after removing `node_modules` just to be sure.

Versions:
- node: v10.19.0
- yarn: v1.22.0
- make: 4.1

### Reproduction scenario

See above

**Comment by RickvdStaaij** [comment]
@syphernl I pushed an update last night, is that what you're experiencing with that fix? I've ran a `make production` installation locally successfully last night

**Comment by RickvdStaaij** [comment]
Oh by the way, this project uses Yarn, not NPM, but I see some changes now locally too, checking what's going on there

**Comment by syphernl** [comment]
> @syphernl I pushed an update last night, is that what you're experiencing with that fix? I've ran a `make production` installation locally successfully last night

`make production` or `make build-production`? The docs say the latter and they didn't work for me without re-running and some other manual tasks.

> Oh by the way, this project uses Yarn, not NPM, but I see some changes now locally too, checking what's going on there. You shouldn't be using `npm install` but `yarn install`

`make build-production` is supposed to deal with everything right? The `npm install` was just in order to (try to) get things back to work.

**Comment by RickvdStaaij** [comment]
@syphernl could you give https://github.com/CIMonitor/CIMonitor/pull/162 a try? I fixed the production dependencies, as some of them were in de the devDependencies, that are required for a production build. Maybe start of with a `rm -rf node_modules/` just to be sure nothing is in the way of a proper install
